[package]
name = "day09"
version = "0.1.0"
authors = ["stumash <stuart.mashaal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
itertools = "0.9.0"
